site_name: Pydantic Prompter Docs
nav:
  - Home: index.md
  - AI services: ai_services.md
  - Prompts: prompt_templates.md
  - Supported models: supported_models.md
theme:
  name: material
  features:
    - content.code.copy
extra:
  analytics:
    provider: google
    property: G-YYQGC0MEXY

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

repo_url: https://github.com/helmanofer/pydantic-prompter
site_url: https://pypi.org/project/pydantic-prompter
