on:
  push:
    branches:
      - '*'
name: run tests
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v5
#        with:
#          python-version: '3.10'
#          cache: 'pip'
#      - run: pip install pdm
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"
          cache: true
      - run: pdm sync
      - run: pdm run pytest
